.cargo_test_template: &cargo_test
  stage: test
  script:
  - rustc --version && cargo --version            # Print version info for debugging
  - time cargo test --verbose --jobs 1 --release  # Don't paralize to make errors more readable

stages:
  - test
  - deploy

stable:cargo:
  image: rustdocker/ubuntu:latest
  <<: *cargo_test

#nightly:cargo:
#  image: rustdocker/rust:nightly
#  <<: *cargo_test

pages:
  image: rustdocker/ubuntu:latest
  stage: deploy
  only:
    - master
  script:
    - cargo doc
    - cargo build --release
    - rm -rf public
    - mkdir public
    - cp -R target/doc/* public
  artifacts:
    paths:
    - public
    - target/release

