[package]
name = "rabe"
version = "0.1.0"
authors = ["Schanzenbach, Martin <martin.schanzenbach@aisec.fraunhofer.de>"]

[dependencies]
bn = "0.4.3"
rand = "0.3"
rust-crypto = "0.2"
rustc-serialize = "~0.3.19"
byteorder = "~0.5.3"
bincode = "0.6.1"
num-bigint = "0.1.40"
