[package]
name = "rabe"
version = "0.1.1"
authors = [
    "Schanzenbach, Martin <martin.schanzenbach@aisec.fraunhofer.de>",
    "Bramm, Georg <georg.bramm@aisec.fraunhofer.de>",
    "Schuette, Julian <julian.schuette@aisec.fraunhofer.de>"
]

[lib]
name="rabe"
crate-type=["rlib", "cdylib"]

[dependencies]
arrayref = "0.3.4"
libc = "0.2.0"
bn = { path = "../bn" }
rand = "0.7.3"
blake2-rfc = "0.2.17"
rust-crypto = "0.2.36"
byteorder = "1.2.2"
bincode = "1.0.0"
num-bigint = "0.1.40"
serde = "1.0.16"
serde_json = "1.0.4"
serde_derive = "1.0.16"
clap = "2.33.1"
