[package]
name = "rabe"
version = "0.2.7"
description = "ABE Schemes implemented in rust."
authors = [
    "Schanzenbach, Martin <martin.schanzenbach@aisec.fraunhofer.de>",
    "Bramm, Georg <georg.bramm@aisec.fraunhofer.de>",
    "Schuette, Julian <julian.schuette@aisec.fraunhofer.de>"
]
keywords = ["pairing","crypto","cryptography", "abe"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Fraunhofer-AISEC/rabe"
repository = "https://github.com/Fraunhofer-AISEC/rabe"
documentation = "https://docs.rs/rabe"

[lib]
name="rabe"
crate-type=["rlib", "cdylib"]
bench = false
path = "src/lib.rs"

[dependencies]
base64 = "0.13.0"
rabe-bn = "0.4.18"
byteorder = "1.2.2"
libc = "0.2.0"
rand = "0.8.5"
serde = "1.0.118"
serde_json = "1.0.60"
serde_cbor = "0.11.1"
serde_derive = "1.0.118"
pest = "2.0"
pest_derive = "2.0"
permutation = "0.2.5"
aes = "0.7.0"
eax = "0.4.1"
sha3 = "0.9.1"