[package]
name = "rabe"
version = "0.1.0"
authors = ["Schanzenbach, Martin <martin.schanzenbach@aisec.fraunhofer.de>"]

[lib]
name="rabe"
crate-type=["dylib"]

[dependencies]
libc = "0.2.0"
bn = { git = "https://github.com/schanzen/bn.git" }
rand = "0.3"
rust-crypto = "0.2"
rustc-serialize = "~0.3.19"
byteorder = "~0.5.3"
bincode = "0.6.1"
num-bigint = "0.1.40"
serde = "1.0.16"
serde_json = "1.0.4"
serde_derive = "1.0.16"
